---
title: "Econometrics II - Assignment 5"
author: "Think of something new"
date: "13 Mar 2022"
output:
  pdf_document:
    includes:
      in_header: "preamble.tex"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(forecast)
library(TSstudio)
library(stringr)
library(zoo)
library(ggplot2)
library(tseries)
library(stats)
library(lmtest)
```

# Question 1

```{r}
# Load data
data <- read.csv("data_assign_p1.csv")
```

1.) 

```{r}
fmt <- "%YQ%q"
data$obs <- as.yearqtr(data$obs, format = fmt)
```


```{r}
ggplot(data, aes(obs, GDP_QGR)) + 
  geom_point() + 
  geom_line() +
  scale_x_yearqtr(format = fmt)
```
```{r}
Acf(
  data$GDP_QGR,
  lag.max = 12
)
```
```{r}
Pacf(
  data$GDP_QGR,
  lag.max = 12
)
```

2.)

```{r}
ar4 <- arima(data$GDP_QGR, order = c(4,0,0))
coeftest(ar4)
```

```{r}
ar3 <- arima(data$GDP_QGR, order = c(3,0,0))
coeftest(ar3)
```

```{r}
ar2 <- arima(data$GDP_QGR, order = c(2,0,0))
coeftest(ar2)
```

```{r}
ar1 <- arima(data$GDP_QGR, order = c(1,0,0))
coeftest(ar1)
```

3.)
```{r}
checkresiduals(ar1)
```

4.)

```{r}
plot(predict(ar1, n.ahead=8)$pred, type="l")
```
```{r}
fore_arima = forecast::forecast(ar1, h=8)
df_arima = as.data.frame(fore_arima)
plot(df_arima$`Point Forecast`, type="l")
```
add to previous graph for sake of visual sanity

5.)

